/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-beacon
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_BEACON_API_H
#define INCLUDED_BEACON_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_beacon_EXPORTS
#define BEACON_API __GR_ATTR_EXPORT
#else
#define BEACON_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_BEACON_API_H */
